
import model.vo.Requerimiento1;
import model.vo.Requerimiento2;
import model.vo.Requerimiento3;
import controller.ControladorRequerimientosReto4;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Robertico
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        
        initComponents();
        JTableExample.setTableHeader(null);
        jScrollPane1.getColumnHeader().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRendererPanel1 = new org.jdesktop.swing.animation.rendering.JRendererPanel();
        jRendererPanel2 = new org.jdesktop.swing.animation.rendering.JRendererPanel();
        rSButtonMaterialGradientOne1 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne2 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne3 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableExample = new RSMaterialComponent.RSTableMetroCustom();
        jLabel1 = new javax.swing.JLabel();
        LblSubTitulo = new javax.swing.JLabel();

        javax.swing.GroupLayout jRendererPanel1Layout = new javax.swing.GroupLayout(jRendererPanel1);
        jRendererPanel1.setLayout(jRendererPanel1Layout);
        jRendererPanel1Layout.setHorizontalGroup(
            jRendererPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jRendererPanel1Layout.setVerticalGroup(
            jRendererPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRendererPanel2.setBackground(new java.awt.Color(51, 0, 51));

        rSButtonMaterialGradientOne1.setBackground(new java.awt.Color(255, 255, 204));
        rSButtonMaterialGradientOne1.setText("Consulta 2");
        rSButtonMaterialGradientOne1.setColorPrimario(new java.awt.Color(0, 0, 0));
        rSButtonMaterialGradientOne1.setColorPrimarioHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialGradientOne1.setColorSecundario(new java.awt.Color(255, 153, 0));
        rSButtonMaterialGradientOne1.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        rSButtonMaterialGradientOne1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMaterialGradientOne1MouseClicked(evt);
            }
        });
        rSButtonMaterialGradientOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne1ActionPerformed(evt);
            }
        });

        rSButtonMaterialGradientOne2.setBackground(new java.awt.Color(255, 255, 204));
        rSButtonMaterialGradientOne2.setText("Consulta 3");
        rSButtonMaterialGradientOne2.setColorPrimario(new java.awt.Color(0, 0, 0));
        rSButtonMaterialGradientOne2.setColorPrimarioHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialGradientOne2.setColorSecundario(new java.awt.Color(255, 153, 0));
        rSButtonMaterialGradientOne2.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        rSButtonMaterialGradientOne2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMaterialGradientOne2MouseClicked(evt);
            }
        });
        rSButtonMaterialGradientOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne2ActionPerformed(evt);
            }
        });

        rSButtonMaterialGradientOne3.setBackground(new java.awt.Color(255, 255, 204));
        rSButtonMaterialGradientOne3.setText("Consulta 1");
        rSButtonMaterialGradientOne3.setColorPrimario(new java.awt.Color(0, 0, 0));
        rSButtonMaterialGradientOne3.setColorPrimarioHover(new java.awt.Color(0, 0, 0));
        rSButtonMaterialGradientOne3.setColorSecundario(new java.awt.Color(255, 153, 0));
        rSButtonMaterialGradientOne3.setColorSecundarioHover(new java.awt.Color(255, 153, 0));
        rSButtonMaterialGradientOne3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMaterialGradientOne3MouseClicked(evt);
            }
        });
        rSButtonMaterialGradientOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne3ActionPerformed(evt);
            }
        });

        JTableExample.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableExample.setBackgoundHead(new java.awt.Color(51, 0, 51));
        JTableExample.setBackgoundHover(new java.awt.Color(255, 153, 0));
        JTableExample.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        JTableExample.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        JTableExample.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JTableExample.setFontHead(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JTableExample.setFontRowHover(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTableExample.setFontRowSelect(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JTableExample.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane1.setViewportView(JTableExample);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reto 5  - Misión Tic UTP ");

        LblSubTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LblSubTitulo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jRendererPanel2Layout = new javax.swing.GroupLayout(jRendererPanel2);
        jRendererPanel2.setLayout(jRendererPanel2Layout);
        jRendererPanel2Layout.setHorizontalGroup(
            jRendererPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRendererPanel2Layout.createSequentialGroup()
                .addGroup(jRendererPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRendererPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(LblSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jRendererPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jRendererPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jRendererPanel2Layout.createSequentialGroup()
                                .addComponent(rSButtonMaterialGradientOne3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(rSButtonMaterialGradientOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSButtonMaterialGradientOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jRendererPanel2Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jRendererPanel2Layout.setVerticalGroup(
            jRendererPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRendererPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(LblSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jRendererPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButtonMaterialGradientOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMaterialGradientOne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMaterialGradientOne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRendererPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRendererPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialGradientOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne3ActionPerformed
        //Btn 1
        LblSubTitulo.setText("Información lideres del proyecto");
        String[] Headers = {"Nombre", "Apellido", "Nro", "Salario"};
        ControladorRequerimientosReto4 controller = new ControladorRequerimientosReto4();

        ArrayList<Requerimiento1> lista;

        try {
            lista = controller.consultarLiderPorSalarios();

            Object[][] data = new Object[lista.size()][4];
            int index = 0;

            for (Requerimiento1 r : lista) {
                data[index][2] = r.getIdLider();
                data[index][0] = r.getNombre();
                data[index][1] = r.getPrimerApellido();
                data[index][3] = r.getSalario();
                index++;
            }

            DefaultTableModel model = new DefaultTableModel(data, Headers);
            JTableExample.setModel(model);
        } catch (SQLException e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_rSButtonMaterialGradientOne3ActionPerformed

    private void rSButtonMaterialGradientOne3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne3MouseClicked

    private void rSButtonMaterialGradientOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne2ActionPerformed
        // Btn 3
        LblSubTitulo.setText("Listado de  lideres del proyecto");
        String[] Headers = {"ID Lider", "Nombre", "Primer apellido"};
        ControladorRequerimientosReto4 controller = new ControladorRequerimientosReto4();

        ArrayList<Requerimiento3> lista;

        try {
            lista = controller.consultarLiderPorNombre();

            Object[][] data = new Object[lista.size()][3];
            int index = 0;

            for (Requerimiento3 r : lista) {
                data[index][0] = r.getIdLider();
                data[index][1] = r.getNombre();
                data[index][2] = r.getPrimerApellido();

                index++;
            }

            DefaultTableModel model = new DefaultTableModel(data, Headers);
            JTableExample.setModel(model);
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_rSButtonMaterialGradientOne2ActionPerformed

    private void rSButtonMaterialGradientOne2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne2MouseClicked

    private void rSButtonMaterialGradientOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne1ActionPerformed
        // Btn 2
        LblSubTitulo.setText("Proyectos por estrato");
        String[] Headers = {"ID Proyecto", "Constructora", "Ciudad", "Estrato"};
        ControladorRequerimientosReto4 controller = new ControladorRequerimientosReto4();

        ArrayList<Requerimiento2> lista;

        try {
            lista = controller.consultarProyectosPorTipo();

            Object[][] data = new Object[lista.size()][4];
            int index = 0;

            for (Requerimiento2 r : lista) {
                data[index][2] = r.getCiudad();
                data[index][1] = r.getConstructora();
                data[index][3] = r.getEstrato();
                data[index][0] = r.getIdProyecto();
                index++;
            }

            DefaultTableModel model = new DefaultTableModel(data, Headers);
            JTableExample.setModel(model);
        } catch (SQLException e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_rSButtonMaterialGradientOne1ActionPerformed

    private void rSButtonMaterialGradientOne1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_rSButtonMaterialGradientOne1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTableMetroCustom JTableExample;
    private javax.swing.JLabel LblSubTitulo;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swing.animation.rendering.JRendererPanel jRendererPanel1;
    private org.jdesktop.swing.animation.rendering.JRendererPanel jRendererPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne1;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne2;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne3;
    // End of variables declaration//GEN-END:variables
}
